require("mlamkadm.core.options")
require("mlamkadm.core.keymaps")
require("mlamkadm.core.terminal")
require("mlamkadm.core.visual").setup()
require("mlamkadm.core.theme").setup()
require("mlamkadm.core.session_manager")
require("mlamkadm.core.ui").setup()
